[WIP] Fix unsafe string path concatenation
rapidsai/tpcx-bb pull request #130
Opened 2020-11-06 16:14 UTC by beckernick

This PR:
- Fixes all remaining unsafe uses of raw string concatenation for paths

2020-11-09 17:31 UTC, beckernick commented
This is now ready for review, cc @ayushdg @VibhuJawa @Christian8491

2020-11-10 19:17 UTC, VibhuJawa requested changes
This almost looks good to merge to me after clarification about the `sentiment_dir`. 

Thanks a lot for the work on fixing this and preventing annoying issues.

2020-11-10 19:17 UTC, VibhuJawa commented on tpcx_bb/queries/q10/tpcx_bb_query_10_sql.py
> +    sentiment_dir = os.path.join(config["data_dir"], "sentiment_files")
Just want to make sure this is intentional as we often save files at 2 directory above this.  

So if the path is  `/raid/tpcx-bb/sf1000/parquet_2gb` the sentiment files were previously placed at ``/raid/tpcx-bb/` . This now assumes the same path as `data_dir` which is better but just want to be sure this is intentional.

2020-11-10 19:17 UTC, VibhuJawa commented on tpcx_bb/queries/q18/tpcx_bb_query_18_sql.py
> +    sentiment_dir = os.path.join(config["data_dir"], "sentiment_files")
Same confirmation here.

2020-11-10 19:20 UTC, VibhuJawa commented on tpcx_bb/queries/q10/tpcx_bb_query_10_sql.py
> +    sentiment_dir = os.path.join(config["data_dir"], "sentiment_files")
This change was intentional (see PR description)

2020-11-10 19:23 UTC, VibhuJawa approved these changes
The pr looks good to go after a minor change to `README.md` about the new path of the `sentiment_dir`.

2020-11-10 19:44 UTC, beckernick commented
Will factor out the blazingsql create table calls into a helper function to avoid duplication in a followup shortly

2020-11-10 19:44 UTC, merged